version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.18.1

    steps:
      - checkout
      - run:
          name: Setup NPM Token
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
      - run:
          name: Install pnpm
          command: sudo npm install --global pnpm
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: build
          command: ASTX_WORKERS=1 pnpm prepublishOnly
      - run:
          name: upload test coverage
          command: pnpm codecov
      - run:
          name: release
          command: ASTX_WORKERS=1 pnpm semantic-release
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - github-release
            - npm-release
